name: Squares CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build project
        run: mvn clean package spring-boot:repackage -B -DskipTests

      - name: Smoke test API
        run: |
          java -jar target/*.jar &
          PID=$!
          sleep 5
          curl -s http://localhost:8080/api/status -H 'Content-Type: application/json' -d '{"size":3,"rows":["...","...","..."],"turn":"WHITE"}'
          kill $PID


